### ISSUE TITLE
Can't compile on Ubuntu 22.04 with neither GCC 11 or 14

### ISSUE THREAD

**Issue by TomClabault** [MircoWerner/ReSTIR-SSS#1]
- I cloned the repository recursively. 
- `cd` into `ReSTIR-SSS/ReSTIRSSS/build` (with the `build` folder I created myself). 
- I disabled OptiX in the `CMakeLists.txt` by setting [line 34](https://github.com/MircoWerner/ReSTIR-SSS/blob/main/ReSTIRSSS/CMakeLists.txt#L34) to `OFF`.
- `cmake -GNinja ..`
- `ninja`

And this yields some compilation errors:

```
[1/6] Building CXX object CMakeFiles/restirsss.dir/src/bin/main.cpp.o
FAILED: CMakeFiles/restirsss.dir/src/bin/main.cpp.o 
/usr/local/gcc-14.1.0/bin/g++-14.1.0 -DRESOURCE_DIRECTORY_PATH=\"/home/tom/Desktop/ReSTIR-SSS/ReSTIRSSS/resources\" -DVULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1 -DVULKAN_HPP_STORAGE_SHARED=1 -I/home/tom/Desktop/ReSTIR-SSS/ReSTIRSSS/include -I/home/tom/Desktop/ReSTIR-SSS/ReSTIRSSS/build/include -I/home/tom/Desktop/ReSTIR-SSS/ReSTIRSSS/src -I/home/tom/Desktop/ReSTIR-SSS/VkRaven/lib/glm -I/home/tom/Desktop/ReSTIR-SSS/VkRaven/lib/glfw/include -I/home/tom/Desktop/ReSTIR-SSS/VkRaven/lib/imgui -I/home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include -I/home/tom/Desktop/ReSTIR-SSS/ReSTIRSSS/build/VkRaven/raven/include -I/home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/../lib -I/home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/../lib/glfw/include -I/home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/../lib/glm -std=gnu++20 -MD -MT CMakeFiles/restirsss.dir/src/bin/main.cpp.o -MF CMakeFiles/restirsss.dir/src/bin/main.cpp.o.d -o CMakeFiles/restirsss.dir/src/bin/main.cpp.o -c /home/tom/Desktop/ReSTIR-SSS/ReSTIRSSS/src/bin/main.cpp
In file included from /home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include/raven/core/Application.h:23,
                 from /home/tom/Desktop/ReSTIR-SSS/ReSTIRSSS/src/bin/main.cpp:7:
/home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include/raven/passes/ImGuiPass.h: In member function ‘void raven::ImGuiPass::recordCommandBuffer(vk::CommandBuffer, vk::Framebuffer)’:
/home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include/raven/passes/ImGuiPass.h:46:79: error: no matching function for call to ‘vk::ClearColorValue::ClearColorValue(<brace-enclosed initializer list>)’
   46 |             clearValues[0].color = {vk::ClearColorValue{0.0f, 0.0f, 0.0f, 1.0f}};
      |                                                                               ^
In file included from /usr/include/vulkan/vulkan.hpp:6770,
                 from /home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include/raven/RavenInclude.h:10,
                 from /home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include/raven/core/GPUContext.h:11,
                 from /home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include/raven/core/Buffer.h:10,
                 from /home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include/raven/core/Application.h:18:
/usr/include/vulkan/vulkan_structs.hpp:12835:29: note: candidate: ‘constexpr vk::ClearColorValue::ClearColorValue(const std::array<unsigned int, 4>&)’
12835 |     VULKAN_HPP_CONSTEXPR_14 ClearColorValue( const std::array<uint32_t, 4> & uint32_ ) : uint32( uint32_ ) {}
      |                             ^~~~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:12835:29: note:   candidate expects 1 argument, 4 provided
/usr/include/vulkan/vulkan_structs.hpp:12833:29: note: candidate: ‘constexpr vk::ClearColorValue::ClearColorValue(const std::array<int, 4>&)’
12833 |     VULKAN_HPP_CONSTEXPR_14 ClearColorValue( const std::array<int32_t, 4> & int32_ ) : int32( int32_ ) {}
      |                             ^~~~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:12833:29: note:   candidate expects 1 argument, 4 provided
/usr/include/vulkan/vulkan_structs.hpp:12831:29: note: candidate: ‘constexpr vk::ClearColorValue::ClearColorValue(const std::array<float, 4>&)’
12831 |     VULKAN_HPP_CONSTEXPR_14 ClearColorValue( const std::array<float, 4> & float32_ = {} ) : float32( float32_ ) {}
      |                             ^~~~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:12831:29: note:   candidate expects 1 argument, 4 provided
/usr/include/vulkan/vulkan_structs.hpp:12826:9: note: candidate: ‘constexpr vk::ClearColorValue::ClearColorValue(const vk::ClearColorValue&)’
12826 |   union ClearColorValue
      |         ^~~~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:12826:9: note:   candidate expects 1 argument, 4 provided
/usr/include/vulkan/vulkan_structs.hpp:12826:9: note: candidate: ‘constexpr vk::ClearColorValue::ClearColorValue(vk::ClearColorValue&&)’
/usr/include/vulkan/vulkan_structs.hpp:12826:9: note:   candidate expects 1 argument, 4 provided
/home/tom/Desktop/ReSTIR-SSS/VkRaven/raven/include/raven/passes/ImGuiPass.h:46:80: error: no match for ‘operator=’ (operand types are ‘vk::ClearColorValue’ and ‘<brace-enclosed initializer list>’)
   46 |             clearValues[0].color = {vk::ClearColorValue{0.0f, 0.0f, 0.0f, 1.0f}};
      |                                                                                ^
/usr/include/vulkan/vulkan_structs.hpp:12826:9: note: candidate: ‘constexpr vk::ClearColorValue& vk::ClearColorValue::operator=(const vk::ClearColorValue&)’
12826 |   union ClearColorValue
      |         ^~~~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:12826:9: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const vk::ClearColorValue&’
/usr/include/vulkan/vulkan_structs.hpp:12826:9: note: candidate: ‘constexpr vk::ClearColorValue& vk::ClearColorValue::operator=(vk::ClearColorValue&&)’
/usr/include/vulkan/vulkan_structs.hpp:12826:9: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘vk::ClearColorValue&&’
ninja: build stopped: subcommand failed.
```
There are also some errors about a conversion:

```
ReSTIR-SSS/VkRaven/raven/src/raven/core/GPUContext.cpp:86:46: error: cannot convert ‘vk::DebugUtilsMessengerCreateInfoEXT’ to ‘VkDebugUtilsMessengerCreateInfoEXT&’
[build]    86 |             populateDebugMessengerCreateInfo(debugCreateInfo);
[build]       |                                              ^~~~~~~~~~~~~~~
[build]       |                                              |
[build]       |                                              vk::DebugUtilsMessengerCreateInfoEXT
```

Has this error already been encountered? Did I miss some steps? I could reproduce this issue on another machine (also Ubuntu 22) with GCC 11.

**Comment by MircoWerner** [comment]
Hi, I've pushed a fix for this on the main branch. Apparently, some calls using the C syntax (as defined in vulkan.h) seem not to work on some systems when including the C++ Vulkan header (vulkan.hpp). I've tried to replace most of the old vulkan.h code. I hope it works for you now!

**Comment by TomClabault** [comment]
I had to tweak a few more things to have it compile on MSVC but it runs now!

![image](https://github.com/user-attachments/assets/d132d4c1-cd03-49ec-a5c0-c45aac620f5c)
